services:
  app:
    build:
      context: .
    ports:
      - "3030:80"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "3031:3001"
    restart: unless-stopped
    env_file:
      - ./backend/.env
