server {
    listen 80;
    server_name localhost;

    # Se a URL começar com /sistemas, servirá da pasta que foi copiada no Dockerfile
    location /sistemas {
        alias /usr/share/nginx/html/sistemas;
        index index.html index.htm;
        try_files $uri $uri/ /sistemas/index.html;
    }

    # Redireciona a raiz (/) para /sistemas/ para facilitar o acesso se digitarem o IP puro
    location = / {
        return 301 /sistemas/;
    }

    # Cache de arquivos estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
